version: '3.1'

volumes:
  mosquitto_data:
    external: true

  dm_pg9_data:
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - mosquitto_data:/mosquitto/data
      - /Users/alexander/go/projects/docker/homekit/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /Users/alexander/go/projects/docker/homekit/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
      - 1883:1883
      - 9001:9001