version: '3.1'

volumes:
  mosquitto_data:
    external: true

  redis_data:
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - mosquitto_data:/mosquitto/data
      - /Users/a.matsenko/go/looplab/homekit/infra/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /Users/a.matsenko/go/looplab/homekit/infra/mosquitto.log:/mosquitto/log/mosquitto.log
    ports:
      - 1883:1883
      - 9001:9001

  redis:
    image: redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6320:6379
    volumes:
      - redis_data:/bitnami