// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TemperatureSensorType int32

const (
	TemperatureSensorType_TemperatureSensorTypeDHT11 TemperatureSensorType = 0
	TemperatureSensorType_TemperatureSensorTypeDHT22 TemperatureSensorType = 1
)

var TemperatureSensorType_name = map[int32]string{
	0: "TemperatureSensorTypeDHT11",
	1: "TemperatureSensorTypeDHT22",
}

var TemperatureSensorType_value = map[string]int32{
	"TemperatureSensorTypeDHT11": 0,
	"TemperatureSensorTypeDHT22": 1,
}

func (x TemperatureSensorType) String() string {
	return proto.EnumName(TemperatureSensorType_name, int32(x))
}

func (TemperatureSensorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

type SwitchInputType int32

const (
	SwitchInputType_SwitchInputTypeOnOff  SwitchInputType = 0
	SwitchInputType_SwitchInputTypePulse  SwitchInputType = 1
	SwitchInputType_SwitchInputTypeChange SwitchInputType = 2
)

var SwitchInputType_name = map[int32]string{
	0: "SwitchInputTypeOnOff",
	1: "SwitchInputTypePulse",
	2: "SwitchInputTypeChange",
}

var SwitchInputType_value = map[string]int32{
	"SwitchInputTypeOnOff":  0,
	"SwitchInputTypePulse":  1,
	"SwitchInputTypeChange": 2,
}

func (x SwitchInputType) String() string {
	return proto.EnumName(SwitchInputType_name, int32(x))
}

func (SwitchInputType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

type ToHub struct {
	ToHub uint32 `protobuf:"varint,1,opt,name=ToHub,proto3" json:"ToHub,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*ToHub_GetContactSensorState
	Message              isToHub_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ToHub) Reset()         { *m = ToHub{} }
func (m *ToHub) String() string { return proto.CompactTextString(m) }
func (*ToHub) ProtoMessage()    {}
func (*ToHub) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *ToHub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToHub.Unmarshal(m, b)
}
func (m *ToHub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToHub.Marshal(b, m, deterministic)
}
func (m *ToHub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToHub.Merge(m, src)
}
func (m *ToHub) XXX_Size() int {
	return xxx_messageInfo_ToHub.Size(m)
}
func (m *ToHub) XXX_DiscardUnknown() {
	xxx_messageInfo_ToHub.DiscardUnknown(m)
}

var xxx_messageInfo_ToHub proto.InternalMessageInfo

func (m *ToHub) GetToHub() uint32 {
	if m != nil {
		return m.ToHub
	}
	return 0
}

type isToHub_Message interface {
	isToHub_Message()
}

type ToHub_GetContactSensorState struct {
	GetContactSensorState *GetContactSensorState `protobuf:"bytes,5,opt,name=GetContactSensorState,proto3,oneof"`
}

func (*ToHub_GetContactSensorState) isToHub_Message() {}

func (m *ToHub) GetMessage() isToHub_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ToHub) GetGetContactSensorState() *GetContactSensorState {
	if x, ok := m.GetMessage().(*ToHub_GetContactSensorState); ok {
		return x.GetContactSensorState
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ToHub) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ToHub_GetContactSensorState)(nil),
	}
}

type GetContactSensorState struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactSensorState) Reset()         { *m = GetContactSensorState{} }
func (m *GetContactSensorState) String() string { return proto.CompactTextString(m) }
func (*GetContactSensorState) ProtoMessage()    {}
func (*GetContactSensorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *GetContactSensorState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactSensorState.Unmarshal(m, b)
}
func (m *GetContactSensorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactSensorState.Marshal(b, m, deterministic)
}
func (m *GetContactSensorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactSensorState.Merge(m, src)
}
func (m *GetContactSensorState) XXX_Size() int {
	return xxx_messageInfo_GetContactSensorState.Size(m)
}
func (m *GetContactSensorState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactSensorState.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactSensorState proto.InternalMessageInfo

func (m *GetContactSensorState) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type ToAccessory struct {
	FromHub uint32 `protobuf:"varint,1,opt,name=FromHub,proto3" json:"FromHub,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*ToAccessory_ContactSensorState
	Message              isToAccessory_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ToAccessory) Reset()         { *m = ToAccessory{} }
func (m *ToAccessory) String() string { return proto.CompactTextString(m) }
func (*ToAccessory) ProtoMessage()    {}
func (*ToAccessory) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *ToAccessory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToAccessory.Unmarshal(m, b)
}
func (m *ToAccessory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToAccessory.Marshal(b, m, deterministic)
}
func (m *ToAccessory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToAccessory.Merge(m, src)
}
func (m *ToAccessory) XXX_Size() int {
	return xxx_messageInfo_ToAccessory.Size(m)
}
func (m *ToAccessory) XXX_DiscardUnknown() {
	xxx_messageInfo_ToAccessory.DiscardUnknown(m)
}

var xxx_messageInfo_ToAccessory proto.InternalMessageInfo

func (m *ToAccessory) GetFromHub() uint32 {
	if m != nil {
		return m.FromHub
	}
	return 0
}

type isToAccessory_Message interface {
	isToAccessory_Message()
}

type ToAccessory_ContactSensorState struct {
	ContactSensorState *ContactSensorState `protobuf:"bytes,5,opt,name=ContactSensorState,proto3,oneof"`
}

func (*ToAccessory_ContactSensorState) isToAccessory_Message() {}

func (m *ToAccessory) GetMessage() isToAccessory_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ToAccessory) GetContactSensorState() *ContactSensorState {
	if x, ok := m.GetMessage().(*ToAccessory_ContactSensorState); ok {
		return x.ContactSensorState
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ToAccessory) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ToAccessory_ContactSensorState)(nil),
	}
}

type ContactSensorState struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	Open                 bool     `protobuf:"varint,2,opt,name=Open,proto3" json:"Open,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactSensorState) Reset()         { *m = ContactSensorState{} }
func (m *ContactSensorState) String() string { return proto.CompactTextString(m) }
func (*ContactSensorState) ProtoMessage()    {}
func (*ContactSensorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *ContactSensorState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactSensorState.Unmarshal(m, b)
}
func (m *ContactSensorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactSensorState.Marshal(b, m, deterministic)
}
func (m *ContactSensorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactSensorState.Merge(m, src)
}
func (m *ContactSensorState) XXX_Size() int {
	return xxx_messageInfo_ContactSensorState.Size(m)
}
func (m *ContactSensorState) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactSensorState.DiscardUnknown(m)
}

var xxx_messageInfo_ContactSensorState proto.InternalMessageInfo

func (m *ContactSensorState) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ContactSensorState) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

type HubConfig struct {
	HubID                uint32          `protobuf:"varint,1,opt,name=HubID,proto3" json:"HubID,omitempty"`
	Devices              []*DeviceConfig `protobuf:"bytes,2,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HubConfig) Reset()         { *m = HubConfig{} }
func (m *HubConfig) String() string { return proto.CompactTextString(m) }
func (*HubConfig) ProtoMessage()    {}
func (*HubConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *HubConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HubConfig.Unmarshal(m, b)
}
func (m *HubConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HubConfig.Marshal(b, m, deterministic)
}
func (m *HubConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HubConfig.Merge(m, src)
}
func (m *HubConfig) XXX_Size() int {
	return xxx_messageInfo_HubConfig.Size(m)
}
func (m *HubConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_HubConfig.DiscardUnknown(m)
}

var xxx_messageInfo_HubConfig proto.InternalMessageInfo

func (m *HubConfig) GetHubID() uint32 {
	if m != nil {
		return m.HubID
	}
	return 0
}

func (m *HubConfig) GetDevices() []*DeviceConfig {
	if m != nil {
		return m.Devices
	}
	return nil
}

type DeviceConfig struct {
	DeviceID uint32 `protobuf:"varint,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*DeviceConfig_ContactSensor
	Config               isDeviceConfig_Config `protobuf_oneof:"Config"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeviceConfig) Reset()         { *m = DeviceConfig{} }
func (m *DeviceConfig) String() string { return proto.CompactTextString(m) }
func (*DeviceConfig) ProtoMessage()    {}
func (*DeviceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *DeviceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceConfig.Unmarshal(m, b)
}
func (m *DeviceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceConfig.Marshal(b, m, deterministic)
}
func (m *DeviceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceConfig.Merge(m, src)
}
func (m *DeviceConfig) XXX_Size() int {
	return xxx_messageInfo_DeviceConfig.Size(m)
}
func (m *DeviceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceConfig proto.InternalMessageInfo

func (m *DeviceConfig) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type isDeviceConfig_Config interface {
	isDeviceConfig_Config()
}

type DeviceConfig_ContactSensor struct {
	ContactSensor *ContactSensorConfig `protobuf:"bytes,2,opt,name=ContactSensor,proto3,oneof"`
}

func (*DeviceConfig_ContactSensor) isDeviceConfig_Config() {}

func (m *DeviceConfig) GetConfig() isDeviceConfig_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *DeviceConfig) GetContactSensor() *ContactSensorConfig {
	if x, ok := m.GetConfig().(*DeviceConfig_ContactSensor); ok {
		return x.ContactSensor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeviceConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeviceConfig_ContactSensor)(nil),
	}
}

type ContactSensorConfig struct {
	InPin                uint32   `protobuf:"varint,1,opt,name=InPin,proto3" json:"InPin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactSensorConfig) Reset()         { *m = ContactSensorConfig{} }
func (m *ContactSensorConfig) String() string { return proto.CompactTextString(m) }
func (*ContactSensorConfig) ProtoMessage()    {}
func (*ContactSensorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *ContactSensorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactSensorConfig.Unmarshal(m, b)
}
func (m *ContactSensorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactSensorConfig.Marshal(b, m, deterministic)
}
func (m *ContactSensorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactSensorConfig.Merge(m, src)
}
func (m *ContactSensorConfig) XXX_Size() int {
	return xxx_messageInfo_ContactSensorConfig.Size(m)
}
func (m *ContactSensorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactSensorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ContactSensorConfig proto.InternalMessageInfo

func (m *ContactSensorConfig) GetInPin() uint32 {
	if m != nil {
		return m.InPin
	}
	return 0
}

// -----------------------
type SetSwitchState struct {
	State                bool     `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetSwitchState) Reset()         { *m = SetSwitchState{} }
func (m *SetSwitchState) String() string { return proto.CompactTextString(m) }
func (*SetSwitchState) ProtoMessage()    {}
func (*SetSwitchState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *SetSwitchState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetSwitchState.Unmarshal(m, b)
}
func (m *SetSwitchState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetSwitchState.Marshal(b, m, deterministic)
}
func (m *SetSwitchState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetSwitchState.Merge(m, src)
}
func (m *SetSwitchState) XXX_Size() int {
	return xxx_messageInfo_SetSwitchState.Size(m)
}
func (m *SetSwitchState) XXX_DiscardUnknown() {
	xxx_messageInfo_SetSwitchState.DiscardUnknown(m)
}

var xxx_messageInfo_SetSwitchState proto.InternalMessageInfo

func (m *SetSwitchState) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

type GetSwitchState struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSwitchState) Reset()         { *m = GetSwitchState{} }
func (m *GetSwitchState) String() string { return proto.CompactTextString(m) }
func (*GetSwitchState) ProtoMessage()    {}
func (*GetSwitchState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *GetSwitchState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSwitchState.Unmarshal(m, b)
}
func (m *GetSwitchState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSwitchState.Marshal(b, m, deterministic)
}
func (m *GetSwitchState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSwitchState.Merge(m, src)
}
func (m *GetSwitchState) XXX_Size() int {
	return xxx_messageInfo_GetSwitchState.Size(m)
}
func (m *GetSwitchState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSwitchState.DiscardUnknown(m)
}

var xxx_messageInfo_GetSwitchState proto.InternalMessageInfo

type GetTemperatureValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTemperatureValue) Reset()         { *m = GetTemperatureValue{} }
func (m *GetTemperatureValue) String() string { return proto.CompactTextString(m) }
func (*GetTemperatureValue) ProtoMessage()    {}
func (*GetTemperatureValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *GetTemperatureValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTemperatureValue.Unmarshal(m, b)
}
func (m *GetTemperatureValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTemperatureValue.Marshal(b, m, deterministic)
}
func (m *GetTemperatureValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTemperatureValue.Merge(m, src)
}
func (m *GetTemperatureValue) XXX_Size() int {
	return xxx_messageInfo_GetTemperatureValue.Size(m)
}
func (m *GetTemperatureValue) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTemperatureValue.DiscardUnknown(m)
}

var xxx_messageInfo_GetTemperatureValue proto.InternalMessageInfo

type SwitchState struct {
	State                bool     `protobuf:"varint,1,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchState) Reset()         { *m = SwitchState{} }
func (m *SwitchState) String() string { return proto.CompactTextString(m) }
func (*SwitchState) ProtoMessage()    {}
func (*SwitchState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *SwitchState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchState.Unmarshal(m, b)
}
func (m *SwitchState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchState.Marshal(b, m, deterministic)
}
func (m *SwitchState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchState.Merge(m, src)
}
func (m *SwitchState) XXX_Size() int {
	return xxx_messageInfo_SwitchState.Size(m)
}
func (m *SwitchState) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchState.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchState proto.InternalMessageInfo

func (m *SwitchState) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

type TemperatureValue struct {
	TemperatureValue     float32  `protobuf:"fixed32,1,opt,name=TemperatureValue,proto3" json:"TemperatureValue,omitempty"`
	HumidityValue        float32  `protobuf:"fixed32,2,opt,name=HumidityValue,proto3" json:"HumidityValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemperatureValue) Reset()         { *m = TemperatureValue{} }
func (m *TemperatureValue) String() string { return proto.CompactTextString(m) }
func (*TemperatureValue) ProtoMessage()    {}
func (*TemperatureValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *TemperatureValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureValue.Unmarshal(m, b)
}
func (m *TemperatureValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureValue.Marshal(b, m, deterministic)
}
func (m *TemperatureValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureValue.Merge(m, src)
}
func (m *TemperatureValue) XXX_Size() int {
	return xxx_messageInfo_TemperatureValue.Size(m)
}
func (m *TemperatureValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureValue.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureValue proto.InternalMessageInfo

func (m *TemperatureValue) GetTemperatureValue() float32 {
	if m != nil {
		return m.TemperatureValue
	}
	return 0
}

func (m *TemperatureValue) GetHumidityValue() float32 {
	if m != nil {
		return m.HumidityValue
	}
	return 0
}

type SwitchConfig struct {
	WithHardwareControl  bool            `protobuf:"varint,1,opt,name=WithHardwareControl,proto3" json:"WithHardwareControl,omitempty"`
	WithSoftwareControl  bool            `protobuf:"varint,2,opt,name=WithSoftwareControl,proto3" json:"WithSoftwareControl,omitempty"`
	WithOutput           bool            `protobuf:"varint,3,opt,name=WithOutput,proto3" json:"WithOutput,omitempty"`
	WithInvertedOutput   bool            `protobuf:"varint,4,opt,name=WithInvertedOutput,proto3" json:"WithInvertedOutput,omitempty"`
	InputPin             uint32          `protobuf:"varint,5,opt,name=InputPin,proto3" json:"InputPin,omitempty"`
	OutputPin            uint32          `protobuf:"varint,6,opt,name=OutputPin,proto3" json:"OutputPin,omitempty"`
	InvertedOutputPin    uint32          `protobuf:"varint,7,opt,name=InvertedOutputPin,proto3" json:"InvertedOutputPin,omitempty"`
	InputType            SwitchInputType `protobuf:"varint,8,opt,name=InputType,proto3,enum=SwitchInputType" json:"InputType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SwitchConfig) Reset()         { *m = SwitchConfig{} }
func (m *SwitchConfig) String() string { return proto.CompactTextString(m) }
func (*SwitchConfig) ProtoMessage()    {}
func (*SwitchConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *SwitchConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchConfig.Unmarshal(m, b)
}
func (m *SwitchConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchConfig.Marshal(b, m, deterministic)
}
func (m *SwitchConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchConfig.Merge(m, src)
}
func (m *SwitchConfig) XXX_Size() int {
	return xxx_messageInfo_SwitchConfig.Size(m)
}
func (m *SwitchConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchConfig proto.InternalMessageInfo

func (m *SwitchConfig) GetWithHardwareControl() bool {
	if m != nil {
		return m.WithHardwareControl
	}
	return false
}

func (m *SwitchConfig) GetWithSoftwareControl() bool {
	if m != nil {
		return m.WithSoftwareControl
	}
	return false
}

func (m *SwitchConfig) GetWithOutput() bool {
	if m != nil {
		return m.WithOutput
	}
	return false
}

func (m *SwitchConfig) GetWithInvertedOutput() bool {
	if m != nil {
		return m.WithInvertedOutput
	}
	return false
}

func (m *SwitchConfig) GetInputPin() uint32 {
	if m != nil {
		return m.InputPin
	}
	return 0
}

func (m *SwitchConfig) GetOutputPin() uint32 {
	if m != nil {
		return m.OutputPin
	}
	return 0
}

func (m *SwitchConfig) GetInvertedOutputPin() uint32 {
	if m != nil {
		return m.InvertedOutputPin
	}
	return 0
}

func (m *SwitchConfig) GetInputType() SwitchInputType {
	if m != nil {
		return m.InputType
	}
	return SwitchInputType_SwitchInputTypeOnOff
}

type TemperatureSensorConfig struct {
	SensorType           TemperatureSensorType `protobuf:"varint,1,opt,name=SensorType,proto3,enum=TemperatureSensorType" json:"SensorType,omitempty"`
	InPin                uint32                `protobuf:"varint,2,opt,name=InPin,proto3" json:"InPin,omitempty"`
	SendInterval         uint32                `protobuf:"varint,3,opt,name=SendInterval,proto3" json:"SendInterval,omitempty"`
	ReadInterval         uint32                `protobuf:"varint,4,opt,name=ReadInterval,proto3" json:"ReadInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TemperatureSensorConfig) Reset()         { *m = TemperatureSensorConfig{} }
func (m *TemperatureSensorConfig) String() string { return proto.CompactTextString(m) }
func (*TemperatureSensorConfig) ProtoMessage()    {}
func (*TemperatureSensorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *TemperatureSensorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureSensorConfig.Unmarshal(m, b)
}
func (m *TemperatureSensorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureSensorConfig.Marshal(b, m, deterministic)
}
func (m *TemperatureSensorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureSensorConfig.Merge(m, src)
}
func (m *TemperatureSensorConfig) XXX_Size() int {
	return xxx_messageInfo_TemperatureSensorConfig.Size(m)
}
func (m *TemperatureSensorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureSensorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureSensorConfig proto.InternalMessageInfo

func (m *TemperatureSensorConfig) GetSensorType() TemperatureSensorType {
	if m != nil {
		return m.SensorType
	}
	return TemperatureSensorType_TemperatureSensorTypeDHT11
}

func (m *TemperatureSensorConfig) GetInPin() uint32 {
	if m != nil {
		return m.InPin
	}
	return 0
}

func (m *TemperatureSensorConfig) GetSendInterval() uint32 {
	if m != nil {
		return m.SendInterval
	}
	return 0
}

func (m *TemperatureSensorConfig) GetReadInterval() uint32 {
	if m != nil {
		return m.ReadInterval
	}
	return 0
}

func init() {
	proto.RegisterEnum("TemperatureSensorType", TemperatureSensorType_name, TemperatureSensorType_value)
	proto.RegisterEnum("SwitchInputType", SwitchInputType_name, SwitchInputType_value)
	proto.RegisterType((*ToHub)(nil), "ToHub")
	proto.RegisterType((*GetContactSensorState)(nil), "GetContactSensorState")
	proto.RegisterType((*ToAccessory)(nil), "ToAccessory")
	proto.RegisterType((*ContactSensorState)(nil), "ContactSensorState")
	proto.RegisterType((*HubConfig)(nil), "HubConfig")
	proto.RegisterType((*DeviceConfig)(nil), "DeviceConfig")
	proto.RegisterType((*ContactSensorConfig)(nil), "ContactSensorConfig")
	proto.RegisterType((*SetSwitchState)(nil), "SetSwitchState")
	proto.RegisterType((*GetSwitchState)(nil), "GetSwitchState")
	proto.RegisterType((*GetTemperatureValue)(nil), "GetTemperatureValue")
	proto.RegisterType((*SwitchState)(nil), "SwitchState")
	proto.RegisterType((*TemperatureValue)(nil), "TemperatureValue")
	proto.RegisterType((*SwitchConfig)(nil), "SwitchConfig")
	proto.RegisterType((*TemperatureSensorConfig)(nil), "TemperatureSensorConfig")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xef, 0x6f, 0xd2, 0x4e,
	0x18, 0xa7, 0xdd, 0x18, 0xf0, 0x30, 0xf8, 0xf6, 0x7b, 0xc0, 0xac, 0x8b, 0x59, 0xc8, 0x69, 0x94,
	0x4c, 0xd3, 0xb8, 0x2e, 0xf1, 0x95, 0x6f, 0xdc, 0xd0, 0x15, 0x13, 0x65, 0x69, 0x89, 0x7b, 0x6b,
	0x81, 0x63, 0x6b, 0x02, 0xd7, 0xe6, 0x7a, 0x65, 0xf2, 0x57, 0xf9, 0xff, 0xf8, 0xd7, 0x98, 0xde,
	0x15, 0xda, 0x42, 0x87, 0xef, 0x78, 0x3e, 0xbf, 0xf2, 0xe9, 0x73, 0x4f, 0x02, 0x34, 0x17, 0x24,
	0x0c, 0xdd, 0x7b, 0x12, 0x1a, 0x01, 0xf3, 0xb9, 0x8f, 0x7f, 0x41, 0x79, 0xe4, 0x5b, 0xd1, 0x18,
	0xb5, 0x93, 0x1f, 0xba, 0xd2, 0x55, 0x7a, 0x0d, 0x3b, 0x41, 0xbf, 0x43, 0xe7, 0x86, 0xf0, 0x6b,
	0x9f, 0x72, 0x77, 0xc2, 0x1d, 0x42, 0x43, 0x9f, 0x39, 0xdc, 0xe5, 0x44, 0x2f, 0x77, 0x95, 0x5e,
	0xdd, 0x3c, 0x31, 0x0a, 0x59, 0xab, 0x64, 0x17, 0xdb, 0xae, 0x6a, 0x50, 0xf9, 0x26, 0x0b, 0xe0,
	0xcb, 0x27, 0xa2, 0xd1, 0x29, 0x54, 0xfb, 0x64, 0xe9, 0x4d, 0xc8, 0xa0, 0x9f, 0x94, 0xd9, 0xcc,
	0x78, 0x05, 0xf5, 0x91, 0xff, 0x69, 0x32, 0x21, 0x61, 0xe8, 0xb3, 0x15, 0xd2, 0xa1, 0xf2, 0x85,
	0xf9, 0x8b, 0xb4, 0xf6, 0x7a, 0x44, 0x9f, 0x01, 0x3d, 0xd9, 0xba, 0x65, 0x14, 0x56, 0x46, 0xfb,
	0xfb, 0xf6, 0x8b, 0x12, 0xf7, 0x95, 0x45, 0x08, 0x0e, 0x87, 0x01, 0xa1, 0xba, 0xda, 0x55, 0x7a,
	0x55, 0x5b, 0xfc, 0xc6, 0x5f, 0xa1, 0x66, 0x45, 0xe3, 0x6b, 0x9f, 0xce, 0xbc, 0xfb, 0x78, 0xe7,
	0x56, 0x34, 0xde, 0x38, 0xe5, 0x80, 0xde, 0x40, 0x45, 0x46, 0x84, 0xba, 0xda, 0x3d, 0xe8, 0xd5,
	0xcd, 0x86, 0x21, 0x67, 0xe9, 0xb2, 0xd7, 0x2c, 0x66, 0x70, 0x9c, 0x25, 0xf6, 0x76, 0xf9, 0x08,
	0x8d, 0x5c, 0x7b, 0x51, 0xaa, 0x6e, 0xb6, 0xf3, 0xab, 0x90, 0x41, 0x56, 0xc9, 0xce, 0x8b, 0xaf,
	0xaa, 0x70, 0x24, 0x29, 0xfc, 0x16, 0x5a, 0x05, 0x8e, 0xf8, 0x4b, 0x06, 0xf4, 0xd6, 0xa3, 0xeb,
	0x2f, 0x11, 0x03, 0x7e, 0x0d, 0x4d, 0x87, 0x70, 0xe7, 0xd1, 0xe3, 0x93, 0x07, 0xb9, 0xae, 0x36,
	0x94, 0xe5, 0x4b, 0x28, 0x62, 0x27, 0x72, 0xc0, 0x1a, 0x34, 0x6f, 0x72, 0x3a, 0xdc, 0x81, 0xd6,
	0x0d, 0xe1, 0x23, 0xb2, 0x08, 0x08, 0x73, 0x79, 0xc4, 0xc8, 0x0f, 0x77, 0x1e, 0x11, 0xfc, 0x12,
	0xea, 0xff, 0x4e, 0x9b, 0x82, 0xb6, 0x6d, 0x44, 0xe7, 0xbb, 0x98, 0x30, 0xa9, 0xf6, 0xae, 0xf6,
	0x15, 0x34, 0xac, 0x68, 0xe1, 0x4d, 0x3d, 0xbe, 0x92, 0x42, 0x55, 0x08, 0xf3, 0x20, 0xfe, 0xa3,
	0xc2, 0xb1, 0xec, 0x92, 0xac, 0xe0, 0x3d, 0xb4, 0xee, 0x3c, 0xfe, 0x60, 0xb9, 0x6c, 0xfa, 0xe8,
	0xb2, 0xf8, 0x4d, 0x38, 0xf3, 0xe7, 0x49, 0xb5, 0x22, 0x6a, 0xed, 0x70, 0xfc, 0x19, 0xcf, 0x3a,
	0xd4, 0xd4, 0xb1, 0x45, 0xa1, 0x33, 0x80, 0x18, 0x1e, 0x46, 0x3c, 0x88, 0xb8, 0x7e, 0x20, 0x84,
	0x19, 0x04, 0x19, 0x80, 0xe2, 0x69, 0x40, 0x97, 0x84, 0x71, 0x32, 0x4d, 0x74, 0x87, 0x42, 0x57,
	0xc0, 0xc4, 0x17, 0x33, 0xa0, 0x41, 0xc4, 0xe3, 0x97, 0x2b, 0xcb, 0x8b, 0x59, 0xcf, 0xe8, 0x05,
	0xd4, 0xa4, 0x2a, 0x26, 0x8f, 0x04, 0x99, 0x02, 0xe8, 0x1d, 0xfc, 0x9f, 0xcf, 0x8a, 0x55, 0x15,
	0xa1, 0xda, 0x25, 0x90, 0x01, 0x35, 0x91, 0x3b, 0x5a, 0x05, 0x44, 0xaf, 0x76, 0x95, 0x5e, 0xd3,
	0xd4, 0x0c, 0xb9, 0xbd, 0x0d, 0x6e, 0xa7, 0x12, 0xfc, 0x5b, 0x81, 0x67, 0x99, 0x77, 0xc9, 0x9d,
	0xda, 0x07, 0x00, 0x39, 0x8b, 0x30, 0x45, 0x84, 0x9d, 0x18, 0x3b, 0x6a, 0x11, 0x99, 0x51, 0xa6,
	0x27, 0xaa, 0x66, 0x4e, 0x14, 0x61, 0x38, 0x76, 0x08, 0x9d, 0x0e, 0x28, 0x27, 0x6c, 0xe9, 0xce,
	0xc5, 0x4e, 0x1b, 0x76, 0x0e, 0x8b, 0x35, 0x36, 0x71, 0x53, 0xcd, 0xa1, 0xd4, 0x64, 0xb1, 0xf3,
	0x3b, 0xe8, 0x14, 0x56, 0x40, 0x67, 0x70, 0x5a, 0x48, 0xf4, 0xad, 0xd1, 0xc5, 0x85, 0x56, 0xda,
	0xc7, 0x9b, 0xa6, 0xa6, 0x9c, 0xff, 0x84, 0xff, 0xb6, 0x16, 0x85, 0x74, 0x68, 0x6f, 0x41, 0x43,
	0x3a, 0x9c, 0xcd, 0xb4, 0x52, 0x01, 0x73, 0x1b, 0xcd, 0x43, 0xa2, 0x29, 0xe8, 0x39, 0x74, 0xb6,
	0x98, 0xeb, 0x07, 0x97, 0xde, 0x13, 0x4d, 0x1d, 0x1f, 0x89, 0x7f, 0x82, 0xcb, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x94, 0x19, 0x0a, 0x10, 0x1b, 0x06, 0x00, 0x00,
}
